# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the
#     filename of the desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Activities
    url: sessions
    identifier: 'activities'
    weight: 10
    
  # under Activities:
  - name: By day
    parent: 'activities'
    url: sessions-by-day
    weight: 13
  - name: By type
    parent: 'activities'
    url: sessions-by-type
    weight: 17

  - name: Schedule
    url: schedule
    weight: 20
  - name: Participants
    url: participants
    weight: 30
  - name: Travel
    url: travel
    weight: 40
  - name: Venues
    url: venues
    weight: 50
  - name: COBS
    url: cobs
    weight: 80
  - name: Contact
    url: contact
    weight: 90
  - name: REGISTER
    url: '#register'
    weight: 100

